export const ActionType = {
  FETCH_GROUPS_STARTED: 'FETCH_GROUPS_STARTED',
  FETCH_GROUPS_SUCCEDED: 'FETCH_GROUPS_SUCCEDED',
  FETCH_GROUPS_FAILED: 'FETCH_GROUPS_FAILED',
  FETCH_GROUP_DETAILS_STARTED: 'FETCH_GROUP_DETAILS_STARTED',
  FETCH_GROUP_DETAILS_SUCCEDED: 'FETCH_GROUP_DETAILS_SUCCEDED',
  FETCH_GROUP_DETAILS_FAILED: 'FETCH_GROUP_DETAILS_FAILED',
}