export const ActionType = {
  FETCH_GROUPS_STARTED: 'FETCH_GROUPS_STARTED',
  FETCH_GROUPS_SUCCEDED: 'FETCH_GROUPS_SUCCEDED',
  FETCH_GROUPS_FAILED: 'FETCH_GROUPS_FAILED',
  FETCH_GROUP_DETAILS_STARTED: 'FETCH_GROUP_DETAILS_STARTED',
  FETCH_GROUP_DETAILS_SUCCEDED: 'FETCH_GROUP_DETAILS_SUCCEDED',
  FETCH_GROUP_DETAILS_FAILED: 'FETCH_GROUP_DETAILS_FAILED',
  SAVING_GROUP_STARTED: 'SAVING_GROUP_STARTED',
  SAVING_GROUP_SUCCEDED: 'SAVING_GROUP_SUCCEDED',
  SAVING_GROUP_FAILED: 'SAVING_GROUP_FAILED',
  DELETING_GROUP_STARTED: 'DELETING_GROUP_STARTED',
  DELETING_GROUP_SUCCEDED: 'DELETING_GROUP_SUCCEDED',
  DELETING_GROUP_FAILED: 'DELETING_GROUP_FAILED'
}